# ===========================================
# Database Configuration (SQLite Only)
# ===========================================

# 개발환경 설정 (SQLite)
development:
  type: sqlite
  name: stock_data.db
  path: ./data/
  echo: false  # SQL 쿼리 로그 출력

# 데이터베이스 테이블 설정
tables:
  # 주식 기본 정보
  # 주식 기본 정보 (OPT10001 데이터 포함)
  stocks:
    table_name: stocks
    columns:
      # 기본 식별 정보
      - { name: code, type: VARCHAR(10), primary_key: true }
      - { name: name, type: VARCHAR(100), nullable: false }
      - { name: market, type: VARCHAR(10) }  # KOSPI, KOSDAQ

      # OPT10001 주식기본정보 데이터
      - { name: current_price, type: INTEGER }      # 현재가
      - { name: prev_day_diff, type: INTEGER }      # 전일대비
      - { name: change_rate, type: FLOAT }          # 등락률
      - { name: volume, type: BIGINT }              # 거래량
      - { name: open_price, type: INTEGER }         # 시가
      - { name: high_price, type: INTEGER }         # 고가
      - { name: low_price, type: INTEGER }          # 저가
      - { name: upper_limit, type: INTEGER }        # 상한가
      - { name: lower_limit, type: INTEGER }        # 하한가
      - { name: market_cap, type: BIGINT }          # 시가총액
      - { name: market_cap_size, type: VARCHAR(20) } # 시가총액규모
      - { name: listed_shares, type: BIGINT }       # 상장주수
      - { name: per_ratio, type: FLOAT }            # PER
      - { name: pbr_ratio, type: FLOAT }            # PBR

      # 메타 정보
      - { name: data_source, type: VARCHAR(20), default: 'OPT10001' }  # 데이터 출처
      - { name: last_updated, type: TIMESTAMP }     # 마지막 업데이트 (5일 체크용)
      - { name: is_active, type: BOOLEAN, default: true }  # 활성 여부
      - { name: created_at, type: TIMESTAMP, default: CURRENT_TIMESTAMP }
      - { name: updated_at, type: TIMESTAMP, default: CURRENT_TIMESTAMP }
    indexes:
      - { name: idx_market, columns: [ market ] }
      - { name: idx_last_updated, columns: [ last_updated ] }
      - { name: idx_is_active, columns: [ is_active ] }
      - { name: idx_market_cap, columns: [ market_cap ] }

  # 일봉 데이터 (opt10081 일봉차트조회)
  daily_prices:
    table_name: daily_prices
    columns:
      - { name: id, type: INTEGER, primary_key: true, auto_increment: true }
      - { name: stock_code, type: VARCHAR(10), nullable: false }
      - { name: date, type: VARCHAR(8), nullable: false }  # YYYYMMDD
      - { name: open_price, type: INTEGER }     # 시가
      - { name: high_price, type: INTEGER }     # 고가
      - { name: low_price, type: INTEGER }      # 저가
      - { name: close_price, type: INTEGER }    # 현재가(종가)
      - { name: volume, type: BIGINT }          # 거래량
      - { name: trading_value, type: BIGINT }   # 거래대금
      - { name: created_at, type: TIMESTAMP, default: CURRENT_TIMESTAMP }
    indexes:
      - { name: idx_stock_date, columns: [stock_code, date], unique: true }
      - { name: idx_date, columns: [date] }